"""add animal, image, adoption

Revision ID: 5e3a62ac551a
Revises: a4adb78a80af
Create Date: 2025-06-23 09:54:36.329302

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "5e3a62ac551a"
down_revision = "a4adb78a80af"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "animal",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("description", sa.TEXT(), nullable=False),
        sa.Column("age_months", sa.Integer(), nullable=False),
        sa.Column("breed", sa.VARCHAR(length=100), nullable=False),
        sa.Column("sex", sa.Enum("MALE", "FEMALE", name="sex"), nullable=False),
        sa.Column(
            "status",
            sa.Enum("AVAILABLE", "ADOPTION", "ADOPTED", name="animalstatus"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_animal")),
    )
    op.create_table(
        "image",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("filename", sa.VARCHAR(length=100), nullable=False),
        sa.Column("mime_type", sa.VARCHAR(length=50), nullable=False),
        sa.Column("animal_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["animal_id"],
            ["animal.id"],
            name=op.f("fk_image_animal_id_animal"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_image")),
    )
    op.create_table(
        "adoption",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("animal_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("submission_date", sa.DATE(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "ACCEPTED",
                "REJECTED",
                "REJECTED_ADOPTED",
                name="adoptionstatus",
            ),
            nullable=False,
        ),
        sa.Column("contact", sa.VARCHAR(length=50), nullable=False),
        sa.ForeignKeyConstraint(
            ["animal_id"],
            ["animal.id"],
            name=op.f("fk_adoption_animal_id_animal"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_adoption_user_id_user")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_adoption")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("adoption")
    op.drop_table("image")
    op.drop_table("animal")
    # ### end Alembic commands ###
