"""fix models

Revision ID: 7e6a8fe95a88
Revises: 5e3a62ac551a
Create Date: 2025-06-23 23:20:43.359706

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7e6a8fe95a88"
down_revision = "5e3a62ac551a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("adoption", schema=None) as batch_op:
        batch_op.drop_constraint(
            "fk_adoption_animal_id_animal", type_="foreignkey"
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_adoption_animal_id_animal"),
            "animal",
            ["animal_id"],
            ["id"],
            ondelete="CASCADE",
        )

    with op.batch_alter_table("animal", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("name", sa.VARCHAR(length=100), nullable=False)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("animal", schema=None) as batch_op:
        batch_op.drop_column("name")

    with op.batch_alter_table("adoption", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_adoption_animal_id_animal"), type_="foreignkey"
        )
        batch_op.create_foreign_key(
            "fk_adoption_animal_id_animal", "animal", ["animal_id"], ["id"]
        )

    # ### end Alembic commands ###
